---

- name: Checking for key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False

- include: install.yml
  tags:
    - newrelic_plugin_mysql

- include: config.yml
  tags:
    - newrelic_plugin_mysql

- include: service.yml
  tags:
    - newrelic_plugin_mysql
